/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpp_kursach_rearrange_figures;

import javax.swing.JTable;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author HELENA_2
 */
public class GameFrame extends javax.swing.JFrame {

    String[][] figurs_position = new String[4][3];
    String[][] finish_position = new String[4][3];
    String v;
    Object click1;
    int c = 0;

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStep = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableField = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableStep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Фигура", "Клетка n-1", "Клетка n"
            }
        ));
        tableStep.setEnabled(false);
        tableStep.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableStep);
        if (tableStep.getColumnModel().getColumnCount() > 0) {
            tableStep.getColumnModel().getColumn(0).setResizable(false);
            tableStep.getColumnModel().getColumn(1).setResizable(false);
            tableStep.getColumnModel().getColumn(2).setResizable(false);
        }

        tableField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableField.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"           0", null, null, null},
                {"           1", null, null, null},
                {"           2", null, null, null}
            },
            new String [] {
                "", "          A", "          B", "          C"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableField.getTableHeader().setReorderingAllowed(false);
        tableField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFieldMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableField);
        if (tableField.getColumnModel().getColumnCount() > 0) {
            tableField.getColumnModel().getColumn(0).setResizable(false);
            tableField.getColumnModel().getColumn(1).setResizable(false);
            tableField.getColumnModel().getColumn(2).setResizable(false);
            tableField.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Таблица ходов");

        btnStart.setText("Начать игру");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Игровое поле");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnStart)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnStart)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Преставь фигуры", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Помощь ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        fill_Field_Table();
    }//GEN-LAST:event_btnStartActionPerformed

   /* private void rools(int x1, int y1, int x2, int y2){
        if(v == "elepanat"){
            if((x2 == x1 + 1 && y2 == y1 + 1)|(x2 == x1 + 1 && y2 == y1 - 1)|
                    (x2 == x1 - 1 && y2 == y1 + 1)|(x2 == x1 - 1 && y2 == y1 - 1)){
                
            }
        }
    }
    */
    private void make_Step(String val,int x1, int y1, int x2, int y2) {
        try{
        figurs_position[x1][y1] = " Fuck ";
        figurs_position[x2][y2] = val;
        System.out.println(x1 + "==== " + y1 + "\n\n" + x2 + "=== " + y2);
        for (int i = 0; i < 3; i++) {    //       Рандомно заполнить
            for (int j = 0; j < 3; j++) {  
                tableField.setValueAt(figurs_position[i][j], i, j + 1);
               // System.out.println("step" + figurs_position[i][j]);
            }      
        }
        }catch (Exception exe){
            System.out.println(exe.getMessage() + "\n\n" + exe.getClass());
        }
    }    

    private boolean empty(int x, int y) {
        boolean a = true;
        x = tableField.getSelectedRow();
        y = tableField.getSelectedColumn();
        String value = tableField.getModel().getValueAt(x, y).toString();
        if (value == " ") {
            System.out.println("No figurse here");
            a = true;
        } else if (value == "elephant" | value == "rook") {
            System.out.println(value);
            v = value;
            a = false;
        }
       return a;
    }

    private void tableFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFieldMouseClicked
        // TODO add your handling code here:

        int x_1 = tableField.getSelectedColumn();
        int y_1 = tableField.getSelectedRow();
        int x_2 = tableField.getSelectedColumn();
        int y_2 = tableField.getSelectedRow();
        empty(y_1, x_1);

        c++;
        if (c == 0) {
        } else if (c % 2 != 0) {
            if (empty(y_1, x_1) == true) {
                JOptionPane.showMessageDialog(jTabbedPane1, "Здесь нет фигуры", "Error", ERROR_MESSAGE);
                c--;
            } else if (empty(y_1, x_1) == false) {
                Object x1 = tableField.getColumnModel().getColumn(x_1).getHeaderValue();
                String y1 = Integer.toString(y_1);
                click1 = x1 + y1;
            }
        } else if (c % 2 == 0) {
            if (empty(y_2, x_2) == false) {            
                JOptionPane.showMessageDialog(jTabbedPane1, "Эта клетка занята", "Error", ERROR_MESSAGE);
                c--;
            } else if (empty(y_2, x_2) == true) {
                Object x2 = tableField.getColumnModel().getColumn(x_2).getHeaderValue();
                String y2 = Integer.toString(y_2);
                Object click2 = x2 + y2;
                tableField_2_Step(v, click1, click2);
                make_Step(v, x_1, y_1, x_2, y_2);
            }
        }
        //tableField_2_Step();
    }//GEN-LAST:event_tableFieldMouseClicked

    private void tableField_2_Step(String v, Object cl1, Object cl2) {
        Vector<Object> step = new Vector(3);
        step.add(v);
        step.add(cl1);
        step.add(cl2);
        DefaultTableModel model = (DefaultTableModel) tableStep.getModel();
        model.addRow(step);
    }

    /**
     * @param args the command line arguments
     */
    private void fill_Field_Table() {
        // ImageIcon icon = new ImageIcon(getClass().getResource("exit.png"));
        /* ImageIcon elephant = new ImageIcon(getClass().getResource("C:\\Users\\HELENA_2\\Desktop\\elephant.png"));
        ImageIcon rook = new ImageIcon(getClass().getResource("C:\\Users\\HELENA_2\\Desktop\\rook.png"));
        String[] columns = {"", "A", "B", "C"};
        Object[][] rows = {{1, rook, elephant, null}, {2, elephant, null, elephant},{3, rook, null, rook}};

        DefaultTableModel model = new DefaultTableModel(rows, columns) {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                    case 1:
                        return Integer.class;
                    case 2:
                        return ImageIcon.class;
                    default:
                        return Object.class;
                }
            }
        };
        tableField = new JTable(model);
         */

        figurs_position[0][0] = "rook";
        figurs_position[0][1] = "elephant";
        figurs_position[0][2] = " ";
        figurs_position[1][0] = "elephant";
        figurs_position[1][1] = " ";
        figurs_position[1][2] = "elephant";
        figurs_position[2][0] = "rook";
        figurs_position[2][1] = " ";
        figurs_position[2][2] = "rook";
        /*for (int i = 0; i < figurs.length; i++) {         //  Рандомно заполнить
            for (int j = 0; j < figurs.length; j++) {
                figurs[i][j] = "yes";
            }
        }*/
        try {
            for (int i = 0; i < 3; i++) {    //       Рандомно заполнить
                for (int j = 0; j < 3; j++) {
                    tableField.setValueAt(figurs_position[i][j], i, j + 1);
                    System.out.println(figurs_position[i][j]);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage() + "\n\n" + e.getClass());
        }
    }
    //____________♗♝_______♖♜______КОНЬ___________________________U+2658

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameFrame frame = new GameFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tableField;
    private javax.swing.JTable tableStep;
    // End of variables declaration//GEN-END:variables
}
